[package]
name = "sniffglue-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.sniffglue]
path = ".."

[[bin]]
name = "read_packet"
path = "fuzz_targets/read_packet.rs"
test = false
doc = false
